package com.myecotrip.myecotrip.network;


public enum ErrorCodes {
    INVALID_USER,
    USER_LOGIN_REQ,
    NO_NETWORK,
    INVALID_STATUS_CODE,
    BAD_INPUT,
    INTERNAL_SERVER_ERROR,
    UNKONN_ERROR,
    JSON_SYNTAX_MISMATCH,
    UN_AUTHORIZED,
    GOOGLE_PLAY_SERVICE_ERROR,
    SERVER_ERROR_RESPONSE

}

